version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: nebula release task and push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew final -Prelease.scope=patch
            else
              ./gradlew snapshot -Prelease.scope=patch
            fi
            ./gradlew dockerPushImage
