version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: maven build
          command: |
            ./gradlew final -Prelease.scope=patch dockerPushImage

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master